const Anthropic = require('@anthropic-ai/sdk');
require('dotenv').config();

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

// Generate content with Veo 3 optimized video prompt
async function generateContentForVeo3(contentType = 'general') {
  
  const systemPrompt = `You are a creative content creator for viral, family-friendly educational YouTube Shorts.

Your job is to create engaging 60-second video concepts that will be brought to life by Google's Veo 3 AI video generator.

IMPORTANT: The video prompt must be HIGHLY DETAILED and CINEMATIC because Veo 3 will generate the ENTIRE VIDEO from your description. No text overlays will be added - the video itself must be captivating.

Create content about: ${contentType}

Return ONLY a JSON object with:
{
  "title": "Catchy title (6-8 words)",
  "subtitle": "Hook line (10-12 words)",
  "veo_prompt": "DETAILED Veo 3 video prompt (see requirements below)",
  "voiceover_script": "Natural narration script (50-55 seconds when read aloud)",
  "content_summary": "Brief summary of the 3 main points covered"
}

VEO 3 PROMPT REQUIREMENTS:
- 150-300 words describing the ENTIRE video shot-by-shot
- Start with establishing shot, include camera movements
- Describe visual style (cinematic, documentary, animated, etc.)
- Specify lighting, colors, mood
- Include transitions between scenes
- Mention key visual moments that sync with narration
- Make it engaging and visually stunning
- 9:16 vertical aspect ratio (YouTube Shorts format)
- Family-friendly, appropriate for all ages

EXAMPLE VEO PROMPT:
"The video opens with a sweeping aerial shot of a vibrant coral reef, sunlight filtering through crystal-clear turquoise water. Camera slowly zooms in to reveal a magnificent purple octopus gracefully swimming through colorful coral formations. Cut to a close-up shot showing the octopus's intelligent eyes and flowing tentacles in stunning detail. The scene transitions with a smooth dissolve to an animated x-ray style view, revealing the octopus's three beating hearts glowing in bioluminescent blue. Camera rotates 360 degrees around the octopus as educational graphics subtly appear and fade, showing the heart locations. Transition back to the natural underwater scene with the octopus now interacting with small fish. The lighting becomes more dramatic with rays of sunlight creating a magical atmosphere. Final shot pulls back to show the octopus swimming away into the blue depths as the camera rises toward the shimmering water surface. Cinematic, nature documentary style, professional color grading, smooth camera movements, 4K quality, mesmerizing and educational."`;

  const userPrompt = `Create an amazing ${contentType} fact video concept for YouTube Shorts.

Make it:
- Fascinating and shareable
- Visually spectacular (remember, Veo 3 will generate the video)
- Educational but entertaining
- Perfect for 60 seconds
- Family-friendly

Focus on topics that will look STUNNING when generated by AI:
- Nature and animals
- Space and cosmos
- Ocean life
- Natural phenomena
- Historical moments
- Scientific discoveries
- Amazing facts about the human body
- Incredible technology

The Veo 3 prompt should describe a complete, cinematic 60-second video that is visually captivating from start to finish.`;

  try {
    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 2000,
      messages: [{
        role: 'user',
        content: systemPrompt + '\n\n' + userPrompt
      }]
    });

    const responseText = message.content[0].text;
    
    // Extract JSON from response
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('No JSON found in Claude response');
    }
    
    const contentData = JSON.parse(jsonMatch[0]);
    contentData.type = contentType;
    
    console.log('Content generated successfully');
    console.log('Title:', contentData.title);
    console.log('Veo Prompt length:', contentData.veo_prompt.length, 'characters');
    
    return contentData;
    
  } catch (error) {
    console.error('Error generating content:', error.message);
    throw error;
  }
}

// Predefined content types
const contentTypes = {
  animals: 'amazing animal facts',
  space: 'fascinating space and astronomy',
  ocean: 'incredible ocean and marine life',
  science: 'mind-blowing science facts',
  history: 'fascinating historical moments',
  nature: 'stunning natural phenomena',
  human_body: 'incredible human body facts',
  technology: 'amazing technology and innovations'
};

// CLI usage
if (require.main === module) {
  const type = process.argv[2] || 'general';
  
  console.log(`Generating ${type} content for Veo 3...`);
  
  generateContentForVeo3(type)
    .then(content => {
      console.log('\n=== GENERATED CONTENT ===\n');
      console.log(JSON.stringify(content, null, 2));
    })
    .catch(error => {
      console.error('Failed:', error.message);
      process.exit(1);
    });
}

module.exports = { generateContentForVeo3, contentTypes };
